version: '3.9'

services:
  postgres:
    container_name: postgres_ecommerce
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - '8001:8001'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    # network_mode: host
    environment:
        STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    command: "listen --forward-to host.docker.internal:3000/payment/webhook/stripe"

volumes:
  postgres-db:
    driver: local
  minio_data:
    driver: local
  redis:
    driver: local